[package]
name = "bulma-defines"
version = "0.1.0"
authors = ["marius <mc.scholtz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common =  { path = "../common" }